title: "#1d5cba"
background: "#ffffff"
border: "#cccccc"
text: "#2a2a2a"
text_em: "#009dc8"
date: "#888888"
path: "#2a2929"
highlight: "#fbe9a4"
shortcut_name: "#00aa00"
header_fg: "#ffffff"
header_bg: "#2741b7"
description: "#808080"
free_text_area_bg: "#f2f2f2"
home_tilde: "#888888"